[main]
database=sqlite+pysqlite:///blackadder.db
; database=sqlite+pysqlite:///:memory:

[paths]
rootfs=/home/yvdev/PrivProjects/blackadder/scripts/GDB/yvos/rootfs:/home/yvdev/PrivProjects/blackadder/scripts/GDB/yvos/zinc
debugfs=/home/yvdev/PrivProjects/blackadder/scripts/GDB/yvos/zinc/opt/zinc/lib/debug
sources=/home/yvdev/sources/devarch:/home/yvdev/sources/yvos-buildroot
